### PR TITLE
Multiple entry points

### PR DESCRIPTION
**Pull request by j8seangel**
Allows component code splitting easily importing the components below the following structure:
`import Component, { SubComponent } from '@globalfishingwatch/map-components/dist/component`

To generate a new bundled component just add an `index.js` file below the component folder and let the 🔮 do its job.

kapture 2019-02-22 at 12 51 59

### CODE REVIEW

**Comment by nerik** [comment]
This is really good. 
I wish there would be a way to do 
```
import { CountryFlag } from '@gfw/map-components/countryflag
```
(without the dist)

Couldn't we do that by creating an index.js file at the root of the repo, setting it as `main`, and have it point to components like this:
```
export { default as CountryFlag } from './dist/countryflag'
```

Might be stupid as honestly I'm not sure I understand how code splitting works.

**Comment by j8seangel** [comment]
We could do it changing the rollup output config and move them to the root level, but for me, having all of them there won't be clean... it also makes harder to clean previous builds (now we remove the `/dist` folder before a new build. 

So I can't find an easy way to fix it apart of setting manually the entry points what make it not worth it.

Easiest thing... do you want to propose a better name rather than `dist`?

**Comment by nerik** [comment]
> We could do it changing the rollup output config and move them to the root level, but for me, having all of them there won't be clean... it also makes harder to clean previous builds (now we remove the `/dist` folder before a new build.

I agree that's why I was suggesting only having an index pointing to individual `/dist/[component]` components.

Having `dist` in an import seems weird - at least not something I ever saw in a library.  But I have no idea how to fix that.

Also it's not _super_ important.

**Comment by j8seangel** [comment]
> I agree that's why I was suggesting only having an index pointing to individual `/dist/[component]` components.

That is what we had before and importing all the components in the same file, even if you don't import those in your app will be included in the final bundle.

> Having `dist` in an import seems weird - at least not something I ever saw in a library. But I have no idea how to fix that.

It depends of the `main` property from the `package.json` and can't have multiple values or a folder.

I've review a couple of [ui](http://react-toolbox.io/#/install) [libraries](https://material-ui.com/) and both has different imports folders for each component. So what about renaming `/dist` to `/components`, or whatever name you prefer, to make it more readable and keep it as it is for now?

**Comment by nerik** [comment]
> So what about renaming /dist to /components, or whatever name you prefer, to make it more readable and keep it as it is for now?

Awesome 👍

**Pull request merged**
